[[data]]
Position = ''
"कर्णाटक-संज्ञा" = ''
"Short name" = ''
Notation = '`Dha'
Mnemonic = ''
"Western note(Sa = C)" = ''
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = 'मन्द्रः ५'
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = 'अनुदात्तः'
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = 'कनिष्ठिकायाम् मध्यमरेखा'
"सामवेदे उत्पत्ति-स्थानम्" = 'रसना'

[[data]]
Position = ''
"कर्णाटक-संज्ञा" = ''
"Short name" = ''
Notation = '`Ni'
Mnemonic = ''
"Western note(Sa = C)" = ''
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = 'अतिस्वार्यः ६'
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = 'उदात्तः'
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = 'कनिष्ठिकायाम् मूलभागः'
"सामवेदे उत्पत्ति-स्थानम्" = 'हृदि'

[[data]]
Position = 1
"कर्णाटक-संज्ञा" = 'षड्ज'
"Short name" = 'Sa'
Notation = 'S'
Mnemonic = 'sa'
"Western note(Sa = C)" = 'C'
"औदीच्य-संज्ञा" = 'Shadj'
Animal = 'peacock'
Chakra = 'mūlādhāra मूलाधार (base of spine)'
"देवः" = 'गणपतिः'
"सामवेदे" = '४'
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = 'स्वरितः'
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = 'अनामिकायाम्'
"सामवेदे उत्पत्ति-स्थानम्" = 'कण्ठः'

[[data]]
Position = 2
"कर्णाटक-संज्ञा" = 'शुद्ध ऋषभ'
"Short name" = 'Ri'
Notation = 'R1'
Mnemonic = 'ra'
"Western note(Sa = C)" = 'D♭'
"औदीच्य-संज्ञा" = 'Komal Rishab'
Animal = 'Bull'
Chakra = 'svādhiṣṭhānaस्वाधिष्ठान (genitals)'
"देवः" = 'अग्निः'
"सामवेदे" = '३'
"प्रकृति-ऋक्सु" = 'अनुदात्तः'
"नारद-शिक्षायाम्" = 'अनुदात्तः'
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = 'मध्यमायाम्'
"सामवेदे उत्पत्ति-स्थानम्" = 'कर्णयोः'

[[data]]
Position = 3
"कर्णाटक-संज्ञा" = 'चतुश्रुति ऋषभ'
"Short name" = 'Ri'
Notation = 'R2'
Mnemonic = 'ri'
"Western note(Sa = C)" = 'D'
"औदीच्य-संज्ञा" = 'Tivra Rishab'
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 3
"कर्णाटक-संज्ञा" = 'शुध्ध गान्धारा'
"Short name" = 'Ga'
Notation = 'G1'
Mnemonic = 'ga'
"Western note(Sa = C)" = 'D'
"औदीच्य-संज्ञा" = 'Komal GA'
Animal = 'goat'
Chakra = 'maṇipūra मणिपूर (solar plexus and navel)'
"देवः" = 'रुद्रः'
"सामवेदे" = '२'
"प्रकृति-ऋक्सु" = 'स्वरितः / आदिमोदात्तः/ उदात्तो यस्माद् अग्रे नास्ति स्वरितावकाशः'
"नारद-शिक्षायाम्" = 'उदात्तः'
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = 'तर्जन्याम्'
"सामवेदे उत्पत्ति-स्थानम्" = 'भ्रूमध्यम्'

[[data]]
Position = 4
"कर्णाटक-संज्ञा" = 'षट्श्रति ऋषभ'
"Short name" = 'Ri'
Notation = 'R3'
Mnemonic = 'ru'
"Western note(Sa = C)" = 'E♭'
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 4
"कर्णाटक-संज्ञा" = 'साधारण गान्धारा'
"Short name" = 'Ga'
Notation = 'G2'
Mnemonic = 'gi'
"Western note(Sa = C)" = 'E♭'
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 5
"कर्णाटक-संज्ञा" = 'अन्तर गान्धारा'
"Short name" = 'Ga'
Notation = 'G3'
Mnemonic = 'gu'
"Western note(Sa = C)" = 'E'
"औदीच्य-संज्ञा" = 'Tivra GA'
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 6
"कर्णाटक-संज्ञा" = 'शुध्ध मध्यम'
"Short name" = 'Ma'
Notation = 'M1'
Mnemonic = 'ma'
"Western note(Sa = C)" = 'F'
"औदीच्य-संज्ञा" = 'Komal MA'
Animal = 'dove/heron'
Chakra = 'anāhata अनाहत (heart)'
"देवः" = 'विष्णुः'
"सामवेदे" = '१'
"प्रकृति-ऋक्सु" = 'उदात्तः'
"नारद-शिक्षायाम्" = 'स्वरितः'
"सामवेदे स्थानम् १" = 'वेणुवाद्यस्य मध्यमस्वरः'
"सामवेदे संज्ञा" = 'अङ्गुष्ठे'
"सामवेदे उत्पत्ति-स्थानम्" = 'ललाटे'

[[data]]
Position = 7
"कर्णाटक-संज्ञा" = 'प्रति मध्यम'
"Short name" = 'Ma'
Notation = 'M2'
Mnemonic = 'mi'
"Western note(Sa = C)" = 'F♯'
"औदीच्य-संज्ञा" = 'Tivra Madhyama'
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 8
"कर्णाटक-संज्ञा" = 'पञ्चम'
"Short name" = 'Pa'
Notation = 'P'
Mnemonic = 'pa'
"Western note(Sa = C)" = 'G'
"औदीच्य-संज्ञा" = 'Pancham'
Animal = 'cuckoo/nightingale'
Chakra = 'viśuddha विशुद्ध (throat)'
"देवः" = 'नारदः'
"सामवेदे" = 'कृष्टः'
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = 'स्वरितः'
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = 'तर्जन्याम् उर्ध्वभागो ३-यवमात्रकः'
"सामवेदे उत्पत्ति-स्थानम्" = 'मूर्धनि'

[[data]]
Position = 9
"कर्णाटक-संज्ञा" = 'शुध्ध धैवता'
"Short name" = 'Dha'
Notation = 'D1'
Mnemonic = 'dha'
"Western note(Sa = C)" = 'A♭'
"औदीच्य-संज्ञा" = 'Komal Da'
Animal = 'Horse'
Chakra = 'ājñā आज्ञा (third eye)'
"देवः" = 'सदाशिवः'
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 10
"कर्णाटक-संज्ञा" = 'चतुश्रति धैवत'
"Short name" = 'Dha'
Notation = 'D2'
Mnemonic = 'dhi'
"Western note(Sa = C)" = 'A'
"औदीच्य-संज्ञा" = 'Thivra Da'
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 10
"कर्णाटक-संज्ञा" = 'शुध्ध निषाद'
"Short name" = 'Ni'
Notation = 'N1'
Mnemonic = 'na'
"Western note(Sa = C)" = 'A'
"औदीच्य-संज्ञा" = ''
Animal = 'elephant'
Chakra = 'sahasrāra सहस्रार (crown of the head)'
"देवः" = 'सूर्यः'
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 11
"कर्णाटक-संज्ञा" = 'षट्श्रुति धैवत'
"Short name" = 'Dha'
Notation = 'D3'
Mnemonic = 'dhu'
"Western note(Sa = C)" = 'B♭'
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 11
"कर्णाटक-संज्ञा" = 'कैशिकी निषाद'
"Short name" = 'Ni'
Notation = 'N2'
Mnemonic = 'ni'
"Western note(Sa = C)" = 'B♭'
"औदीच्य-संज्ञा" = 'Komal NI'
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 12
"कर्णाटक-संज्ञा" = 'काकली निषाद'
"Short name" = 'Ni'
Notation = 'N3'
Mnemonic = 'nu'
"Western note(Sa = C)" = 'B'
"औदीच्य-संज्ञा" = 'Tivra NI'
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = ''
"कर्णाटक-संज्ञा" = ''
"Short name" = ''
Notation = ''
Mnemonic = ''
"Western note(Sa = C)" = ''
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 'सामवेदे उपस्वराः'
"कर्णाटक-संज्ञा" = ''
"Short name" = ''
Notation = ''
Mnemonic = ''
"Western note(Sa = C)" = ''
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 'प्रयङ्कम्'
"कर्णाटक-संज्ञा" = ''
"Short name" = ''
Notation = ''
Mnemonic = ''
"Western note(Sa = C)" = ''
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 'विनतम्'
"कर्णाटक-संज्ञा" = ''
"Short name" = ''
Notation = ''
Mnemonic = ''
"Western note(Sa = C)" = ''
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 'नमनम्'
"कर्णाटक-संज्ञा" = ''
"Short name" = ''
Notation = ''
Mnemonic = ''
"Western note(Sa = C)" = ''
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 'अभिगीतम्'
"कर्णाटक-संज्ञा" = ''
"Short name" = ''
Notation = ''
Mnemonic = ''
"Western note(Sa = C)" = ''
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''

[[data]]
Position = 'सम्प्रसारणम्'
"कर्णाटक-संज्ञा" = ''
"Short name" = ''
Notation = ''
Mnemonic = ''
"Western note(Sa = C)" = ''
"औदीच्य-संज्ञा" = ''
Animal = ''
Chakra = ''
"देवः" = ''
"सामवेदे" = ''
"प्रकृति-ऋक्सु" = ''
"नारद-शिक्षायाम्" = ''
"सामवेदे स्थानम् १" = ''
"सामवेदे संज्ञा" = ''
"सामवेदे उत्पत्ति-स्थानम्" = ''
